import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import { Roboto } from "next/font/google";
import TransitionProvider from "./components/transitionProvider";

const roboto = Roboto({
  subsets: ['latin'],
  variable: "--font-roboto",
  weight: '500',
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body
        className={`${roboto.variable} ${roboto.variable} font-sans`}
      >
        <TransitionProvider> { children } </TransitionProvider>
      </body>
    </html>
  );
}
